backend:
  name: git-gateway
  accept_roles:
    - admin
    - editor
media_folder: theme/assets/images
public_folder: /assets/images
collections:
  - name: pages
    label: Pages
    identifier_field: title
    extension: md
    create: false
    delete: false
    slug: '{{slug}}'
    editor:
      preview: false
    folder: cms/pages
    fields:
      - label: Title
        name: title
        widget: string
      - label: Publish Date
        name: date
        widget: datetime
      - label: Layout
        widget: hidden
        name: layout
        default: '{{slug}}.html'
      - &ref_0
        label: Seo
        name: seo
        widget: object
        collapsed: true
        fields:
          - label: Title
            name: title
            widget: string
            required: false
          - label: Description
            name: description
            widget: string
            required: false
          - label: No index
            name: noindex
            widget: boolean
            default: false
            required: false
          - label: Open Graph Title
            name: og:title
            widget: string
            required: false
          - label: Open Graph Image
            name: og:image
            widget: image
            required: false
            media_library:
              config:
                multiple: false
          - label: Twitter Title
            name: twitter:title
            widget: string
            default: summary
            required: false
          - label: Twitter Card
            name: twitter:card
            widget: string
            default: summary
            required: false
          - label: Twitter Site
            name: twitter:site
            widget: string
            required: false
          - label: Twitter Creator
            name: twitter:creator
            widget: string
            required: false
          - label: Additional HTML tags
            name: additional_tags
            widget: text
            required: false
  - name: publications
    label: Publications
    folder: cms/publications
    create: true
    identifier_field: name
    extension: md
    slug: '{{slug}}'
    fields:
      - hint: ''
        name: title
        label: Name
        widget: string
        required: true
      - hint: ''
        name: created-on
        label: Created On
        widget: datetime
        required: false
      - hint: ''
        name: updated-on
        label: Updated On
        widget: datetime
        required: false
      - hint: ''
        name: published-on
        label: Published On
        widget: datetime
        required: false
      - label: Tags
        widget: hidden
        name: tags
        default: publications
      - label: Layout
        widget: hidden
        name: layout
        default: '[publications].html'
      - label: Publish Date
        name: date
        widget: datetime
      - *ref_0
  - name: media_coverage
    label: Media Coverages
    folder: cms/media-coverage
    create: true
    identifier_field: name
    extension: md
    slug: '{{slug}}'
    fields:
      - hint: ''
        name: title
        label: Name
        widget: string
        required: true
      - hint: ''
        name: created-on
        label: Created On
        widget: datetime
        required: false
      - hint: ''
        name: updated-on
        label: Updated On
        widget: datetime
        required: false
      - hint: ''
        name: published-on
        label: Published On
        widget: datetime
        required: false
      - hint: Direct link to the Article
        name: f_article-url
        label: Article URL
        widget: string
        required: false
      - hint: ''
        name: f_publication
        label: Publication
        widget: relation
        required: true
        collection: publications
        value_field: cms/publications/{{slug}}.md
        search_fields:
          - slug
          - name
        display_fields:
          - title
        multiple: false
      - hint: ''
        name: f_image
        label: Image
        widget: object
        required: false
        fields:
          - hint: ''
            name: url
            label: Image
            widget: image
            required: false
            allow_multiple: false
          - hint: Image Alt
            name: alt
            label: alt
            widget: string
            required: false
      - label: Tags
        widget: hidden
        name: tags
        default: media-coverage
      - label: Layout
        widget: hidden
        name: layout
        default: '[media-coverage].html'
      - label: Publish Date
        name: date
        widget: datetime
      - *ref_0
  - name: blog
    label: Press Releases
    folder: cms/blog
    create: true
    identifier_field: name
    extension: md
    slug: '{{slug}}'
    fields:
      - hint: ''
        name: title
        label: Name
        widget: string
        required: true
      - hint: ''
        name: created-on
        label: Created On
        widget: datetime
        required: false
      - hint: ''
        name: updated-on
        label: Updated On
        widget: datetime
        required: false
      - hint: ''
        name: published-on
        label: Published On
        widget: datetime
        required: false
      - label: Post Body
        name: body
        widget: markdown
        required: false
      - hint: What category does this post fall in?
        name: f_category-2
        label: Category
        widget: relation
        required: true
        collection: categories
        value_field: cms/categories/{{slug}}.md
        search_fields:
          - slug
          - name
        display_fields:
          - title
        multiple: false
      - hint: Who wrote this post?
        name: f_author-2
        label: Author
        widget: relation
        required: false
        collection: authors
        value_field: cms/authors/{{slug}}.md
        search_fields:
          - slug
          - name
        display_fields:
          - title
        multiple: false
      - hint: A summary of the blog post that appears on blog post grid
        name: f_post-summary
        label: Post Summary
        widget: text
        required: false
      - hint: Smaller version of main image that is used on blog post grid
        name: f_thumbnail-image
        label: Thumbnail image
        widget: object
        required: false
        fields:
          - hint: ''
            name: url
            label: Image
            widget: image
            required: false
            allow_multiple: false
          - hint: Image Alt
            name: alt
            label: alt
            widget: string
            required: false
      - hint: ''
        name: f_main-image
        label: Main Image
        widget: object
        required: false
        fields:
          - hint: ''
            name: url
            label: Image
            widget: image
            required: false
            allow_multiple: false
          - hint: Image Alt
            name: alt
            label: alt
            widget: string
            required: false
      - label: Tags
        widget: hidden
        name: tags
        default: blog
      - label: Layout
        widget: hidden
        name: layout
        default: '[blog].html'
      - label: Publish Date
        name: date
        widget: datetime
      - *ref_0
  - name: categories
    label: Press Release Categories
    folder: cms/categories
    create: true
    identifier_field: name
    extension: md
    slug: '{{slug}}'
    fields:
      - hint: ''
        name: title
        label: Name
        widget: string
        required: true
      - hint: ''
        name: created-on
        label: Created On
        widget: datetime
        required: false
      - hint: ''
        name: updated-on
        label: Updated On
        widget: datetime
        required: false
      - hint: ''
        name: published-on
        label: Published On
        widget: datetime
        required: false
      - hint: Add a short description about the post category here.
        name: f_short-description
        label: Short Description
        widget: text
        required: false
      - label: Tags
        widget: hidden
        name: tags
        default: categories
      - label: Layout
        widget: hidden
        name: layout
        default: '[categories].html'
      - label: Publish Date
        name: date
        widget: datetime
      - *ref_0
  - name: authors
    label: Authors
    folder: cms/authors
    create: true
    identifier_field: name
    extension: md
    slug: '{{slug}}'
    fields:
      - hint: ''
        name: title
        label: Name
        widget: string
        required: true
      - hint: ''
        name: created-on
        label: Created On
        widget: datetime
        required: false
      - hint: ''
        name: updated-on
        label: Updated On
        widget: datetime
        required: false
      - hint: ''
        name: published-on
        label: Published On
        widget: datetime
        required: false
      - hint: Add an image of the author here.
        name: f_avatar
        label: Avatar
        widget: object
        required: false
        fields:
          - hint: ''
            name: url
            label: Image
            widget: image
            required: false
            allow_multiple: false
          - hint: Image Alt
            name: alt
            label: alt
            widget: string
            required: false
      - hint: Add a few sentences about the author here.
        name: f_bio
        label: Bio
        widget: text
        required: false
      - label: Tags
        widget: hidden
        name: tags
        default: authors
      - label: Layout
        widget: hidden
        name: layout
        default: '[authors].html'
      - label: Publish Date
        name: date
        widget: datetime
      - *ref_0
  - label: Theme Settings
    name: settings
    identifier_field: title
    extension: json
    create: false
    delete: false
    slug: '{{slug}}'
    editor:
      preview: false
    files:
      - label: General
        name: site
        file: cms/_data/settings/site.json
        fields:
          - label: Title
            name: title
            widget: hidden
            default: General
          - hint: Full domain url (needed for a correct sitemap file)
            name: domain
            label: Domain
            widget: string
            required: false
          - name: favicon
            label: Favicon
            widget: image
            allow_multiple: false
            required: false
          - name: apple_touch_icon
            label: Apple Touch Icon
            widget: image
            allow_multiple: false
            required: false
          - name: header_additional_content
            label: Additional Content Header
            hint: Content here will be placed before </head> tag
            widget: text
            required: false
          - name: footer_additional_content
            label: Additional Content Footer
            hint: Content here will be placed before </body> tag
            widget: text
            required: false
          - name: images_optimization
            label: Images Optimization
            widget: object
            collapsed: false
            fields:
              - label: Image Formats
                name: formats
                widget: select
                multiple: true
                options:
                  - label: Avif
                    value: avif
                  - label: Webp
                    value: webp
              - label: Image Dimensions
                name: dimensions
                widget: select
                multiple: true
                options:
                  - label: '500'
                    value: 500
                  - label: '800'
                    value: 800
                  - label: '1080'
                    value: 1080
                  - label: '1600'
                    value: 1600
                  - label: '2000'
                    value: 2000
                  - label: '2600'
                    value: 2600
      - label: Colors
        name: colors
        file: cms/_data/colors.json
        fields:
          - label: Title
            name: title
            widget: hidden
            default: Colors
      - label: Images
        name: images
        file: cms/_data/images.json
        fields:
          - label: Title
            name: title
            widget: hidden
            default: Images
          - label: Image
            name: 24abdf23
            widget: object
            fields:
              - name: url
                label: Image Url
                widget: image
                allow_multiple: false
                required: false
              - name: alt
                label: Image Alt
                widget: string
                required: false
publish_mode: editorial_workflow
